services:
  # The Nginx reverse proxy service
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/etc:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./codeeve/html:/var/www/codeeve/html:ro
    networks:
      - public-network

  # The Certbot service for HTTPS certificate renewal
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: no
    # Renew certificates and reload Nginx on every docker Compose up - this is not an ideal way to renew certs, consider using a CRON job or a separate service for production use
    #command: renew --quiet && nginx -s reload

# Create a shared network for all your services
networks:
  public-network:
    name: public-network
    external: true

